version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  mongo-db:
    image: mongo:4.4
    container_name: all-scans-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: all-scans-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo-db:27017
      - MONGO_DB_NAME=All_scans
    depends_on:
      - mongo-db
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: all-scans-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://127.0.0.1:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # CETTE LIGNE SAUVE LA SITUATION :
    command: sh -c "npm install && npm start"
    networks:
      - app-network

volumes:
  mongo-data: